version: '3.8'

services:
  # 1. 관계형 데이터베이스 (MariaDB)
  mariadb:
    image: mariadb:10.11
    container_name: pcs-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql

  # 2. 인메모리 캐시 (Redis) - JWT 및 성능 최적화용
 # redis:
 #   image: redis:7-alpine # 가벼운 알파인 리눅스 버전 사용
 #   container_name: fitness-redis
 #   ports:
 #     - "6379:6379" # Redis의 기본 포트
 #   volumes:
 #     - redis_data:/data

volumes:
  mariadb_data:
  redis_data: